### ISSUE TITLE
Warning: Unexpected end of wights-file! l.biases - l.index = 0  Done! Loaded 0 layers from weights-file 

### ISSUE THREAD

**Issue by Ljincheng0128** [anabdck/pcb-defect-detection-api#1]
I followed the steps to run, but the displayed picture is not marked, and the content of the generated txt file is empty. What could be my execution error? Thanks, and the log is printed as follows,
 Try to load weights: /home/ruirui/Desktop/pcb/app/controllers/Darknet/yolov4_custom.weights 
Loading weights from /home/ruirui/Desktop/pcb/app/controllers/Darknet/yolov4_custom.weights...
 seen 32, trained: 791624 K-images (12369 Kilo-batches_64) 

 Warning: Unexpected end of wights-file! l.biases - l.index = 0 
Done! Loaded 0 layers from weights-file 
Loaded - names_list: /home/ruirui/Desktop/pcb/app/controllers/Darknet/obj.names, classes = 6 
🦖 tempo de carregamento: 2.44 segundos
 * Debugger is active!
 * Debugger PIN: 319-008-916
![@AYI8Z(87(J)QE0 X~W~I}J](https://user-images.githubusercontent.com/51052462/128961076-042be249-048d-4a3f-aeb0-4b6068db5393.png)

**Comment by anabdck** [comment]
you can try to [download the weights](https://drive.google.com/uc?id=1BNH79y7Dq5upak96b8bakMkPh4J0RSvX&export=download) and replace it in the folder `pcb-defect-detection-api/app/controllers/Darknet`

**Comment by Ljincheng0128** [comment]
Problem solved, thank you
